### ISSUE TITLE
Down frequency gets corrupted between MQTT → Semtech UDP packets

### ISSUE THREAD

**Issue by lukecyca** [chirpstack/chirpstack-mqtt-forwarder#50]
Some background to my issue and troubleshooting is located in this forum post:
https://forum.chirpstack.io/t/dragino-lps8n-with-mqtt-forwarder-uses-wrong-downlink-frequency

I believe I've isolated this to the `chirpstack-mqtt-forwarder`. The frequency specified by the LNS is modified when passed on to the gateway.

Here is a `JOIN_ACCEPT` MQTT packet from the LNS:
```json
{
  "phyPayload": "IOjGEhU69v5h54skpaMbdSROCQVfcyzw+AKLl5fsZM8t",
  "txInfo": {
    "frequency": 923300000,
    "power": 21,
    "modulation": {
      "lora": {
        "bandwidth": 500000,
        "spreadingFactor": 12,
        "codeRate": "CR_4_5",
        "polarizationInversion": true
      }
    },
    "timing": {
      "delay": {
        "delay": "6s"
      }
    },
    "context": "PQcQKQ=="
  }
}
```

And the corresponding semtech_udp TxPk:
```json
{
  "imme": false,
  "rfch": 0,
  "powe": 21,
  "ant": 0,
  "brd": 0,
  "tmst": 1028873064,
  "tmms": null,
  "freq": 268.435632,
  "modu": "LORA",
  "datr": "SF10BW500",
  "codr": "4/5",
  "fdev": null,
  "ncrc": null,
  "ipol": true,
  "prea": null,
  "size": 33,
  "data": "IOjGEhU69v5h54skpaMbdSROCQVfcyzw+AKLl5fsZM8t"
}
```

Notice that the frequency is correct in the MQTT packet, and incorrect in the Semtech UDP packet.

It's always `268.abcdef` where the decimals change a bit each time.

Version: chirpstack-mqtt-forwarder 4.1.3

Here is my config:
```toml
[logging]
  level="info"
  log_to_syslog=false

[backend]
  enabled="semtech_udp"

  [backend.semtech_udp]
    udp_bind="0.0.0.0:1700"

[mqtt]
  topic_prefix="us915_0"
  json=true
  server="wss://mqtt.test.example.com/mqtt"
  username="redacted"
  password="redacted"
  ca_cert="/etc/ssl/cert.pem"
  tls_cert=""
  tls_key=""
```
